import { Inter } from "next/font/google";
import Header from "@/components/layout/Header";
import "@/scss/main.scss";
import { ChildrenProps } from "@/types/common";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: 'swap'
});

export const metadata = {
  title: "Main Page",
  description: "Generated by Artilab",
};

export default function RootLayout({ children }: ChildrenProps) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <Header />
        <main className="page-wrapper">
          {children}
        </main>
      </body>
    </html>
  );
}
