import {Inter} from "next/font/google";
import Header from "@/components/layout/Header";
import "@/scss/main.scss";
import {ChildrenProps} from "@/types/common";
import {AuthProvider} from "@/context/AuthContext";
import {cookies} from "next/headers";
import AuthGuard from "@/app/AuthGuard";

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
	display: 'swap'
});

export const metadata = {
	title: "Main Page",
	description: "Generated by Artilab",
};

export default async function RootLayout({children}: ChildrenProps) {
	const cookieStore = await cookies();
	const token = !!cookieStore.get('auth_token')?.value;
	
	return (
		<html lang="en">
		<body className={`${inter.variable}`}>
		<AuthProvider status={token}>
			<AuthGuard>
				<Header/>
				<main className="page-wrapper">
					{children}
				</main>
			</AuthGuard>
		</AuthProvider>
		</body>
		</html>
	);
}
